# Cloud Build configuration for Atlas Game Server
# Builds and deploys to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/atlas-game-server:$COMMIT_SHA', '.']
    dir: 'game-server'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/atlas-game-server:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'atlas-game-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/atlas-game-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--session-affinity'

images:
  - 'gcr.io/$PROJECT_ID/atlas-game-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
