// ─────────────────────────────────────────────────────────────────────────────
// Shared game data — single source of truth for games, categories, search
// ─────────────────────────────────────────────────────────────────────────────

export const gameCategories = {
  mechanics: { name: 'Mechanics', icon: '⚙️', color: '#3B82F6', description: 'Forces, motion, and energy' },
  thermodynamics: { name: 'Thermo', icon: '🔥', color: '#EF4444', description: 'Heat, temperature, and energy transfer' },
  electromagnetism: { name: 'E&M', icon: '⚡', color: '#F59E0B', description: 'Electric and magnetic phenomena' },
  waves: { name: 'Waves & Optics', icon: '🌊', color: '#8B5CF6', description: 'Light, sound, and wave behavior' },
  fluids: { name: 'Fluids', icon: '💧', color: '#06B6D4', description: 'Liquids, gases, and flow' },
  modern: { name: 'Modern', icon: '⚛️', color: '#EC4899', description: 'Quantum and modern physics' },
  engineering: { name: 'Engineering', icon: '🔧', color: '#10B981', description: 'Applied physics and power systems' },
  computing: { name: 'Computing & AI', icon: '💻', color: '#6366F1', description: 'Hardware, AI, and ML concepts' },
  semiconductor: { name: 'Semiconductor', icon: '🔬', color: '#14B8A6', description: 'Chip design and fabrication' },
  solar: { name: 'Solar & PV', icon: '☀️', color: '#FBBF24', description: 'Solar cells and photovoltaics' },
  elon: { name: 'ELON', icon: '🚀', color: '#F97316', description: 'Systems thinking across energy, space, chips' },
};

export type GameCategoryKey = keyof typeof gameCategories;

export const searchTags: Record<string, string[]> = {
  'center-of-mass': ['balance', 'gravity', 'equilibrium', 'COM'],
  'momentum-conservation': ['collision', 'crash', 'impact', 'p=mv'],
  'angular-momentum': ['spin', 'rotation', 'L=Iw'],
  'angular-momentum-transfer': ['spin', 'rotation', 'ice skater'],
  'projectile-independence': ['throw', 'launch', 'trajectory', 'horizontal vertical'],
  'torque': ['lever', 'wrench', 'rotation', 'moment'],
  'inclined-plane': ['ramp', 'slope', 'angle', 'friction'],
  'hookes-law': ['spring', 'elastic', 'F=kx', 'stretch'],
  'pendulum-period': ['swing', 'clock', 'T=2pi', 'SHM'],
  'inertia': ['mass', 'resistance', 'Newton first law'],
  'newtons-third-law': ['action reaction', 'equal opposite', 'N3L'],
  'static-kinetic-friction': ['slip', 'slide', 'mu', 'coefficient'],
  'rolling-vs-sliding': ['wheel', 'tire', 'roll', 'slide'],
  'moment-of-inertia': ['rotational mass', 'I=mr2', 'flywheel'],
  'gyroscopic-precession': ['gyro', 'spin', 'wobble', 'bicycle'],
  'two-ball-collision': ['elastic', 'bounce', 'billiard'],
  'inelastic-collisions': ['sticky', 'deform', 'energy loss'],
  'ballistic-pendulum': ['bullet', 'projectile', 'momentum energy'],
  'egg-drop': ['impact', 'cushion', 'protection', 'force'],
  'orbital-mechanics': ['orbit', 'satellite', 'Kepler', 'gravity'],
  'orbital-mechanics-basics': ['orbit', 'satellite', 'Kepler', 'gravity'],
  'tidal-forces': ['moon', 'ocean', 'gravity gradient', 'bulge'],
  'tidal-locking': ['moon', 'synchronous', 'rotation period'],
  'coriolis-effect': ['rotation', 'wind', 'hurricane', 'deflection'],
  'bottle-tornado': ['vortex', 'spin', 'water'],
  'brownian-motion': ['random walk', 'particles', 'diffusion', 'pollen'],
  'centripetal-force': ['circular', 'radius', 'spin', 'orbit'],
  'carnot-cycle': ['engine', 'efficiency', 'heat engine', 'PV diagram'],
  'entropy': ['disorder', 'second law', 'thermodynamics', 'S'],
  'thermal-expansion': ['heat', 'expand', 'contract', 'coefficient'],
  'thermal-contact': ['heat transfer', 'conduction', 'temperature'],
  'newton-cooling': ['cooling curve', 'temperature', 'exponential'],
  'convection': ['heat flow', 'rising', 'fluid circulation'],
  'gas-laws': ['PV=nRT', 'ideal gas', 'Boyle', 'Charles'],
  'phase-change-energy': ['melting', 'freezing', 'boiling', 'latent heat'],
  'latent-heat': ['melting', 'boiling', 'phase change', 'energy'],
  'kinetic-theory-gases': ['molecules', 'speed', 'temperature', 'pressure'],
  'wave-interference': ['constructive', 'destructive', 'superposition'],
  'wave-speed-tension': ['string', 'frequency', 'wavelength'],
  'diffraction': ['slit', 'grating', 'pattern', 'bending'],
  'snells-law': ['refraction', 'angle', 'n1 sin', 'glass'],
  'doppler-effect': ['frequency shift', 'ambulance', 'redshift'],
  'resonance': ['natural frequency', 'amplitude', 'oscillation'],
  'photoelectric-effect': ['photon', 'electron', 'Einstein', 'threshold'],
  'coulombs-law': ['charge', 'force', 'electrostatic', 'q1q2'],
  'electric-field': ['charge', 'force field', 'E=F/q'],
  'magnetic-field': ['magnet', 'compass', 'B field', 'Tesla'],
  'electromagnetic-induction': ['Faraday', 'EMF', 'generator', 'flux'],
  'kirchhoffs-laws': ['circuit', 'KVL', 'KCL', 'voltage current'],
  'circuits': ['resistor', 'series', 'parallel', 'Ohm'],
  'r-c-time-constant': ['capacitor', 'charge', 'discharge', 'tau'],
  'transformer': ['voltage', 'turns ratio', 'step up', 'step down'],
  'bernoulli': ['pressure', 'velocity', 'fluid flow', 'airplane'],
  'buoyancy': ['float', 'sink', 'Archimedes', 'density'],
  'pascal-law': ['pressure', 'hydraulic', 'piston'],
  'hydrostatic-pressure': ['depth', 'water', 'rho g h'],
  'venturi-effect': ['constriction', 'pressure drop', 'flow speed'],
  'laminar-turbulent': ['Reynolds', 'flow', 'smooth', 'chaotic'],
  'solar-cell': ['photovoltaic', 'PV', 'electricity', 'sunlight'],
  'm-o-s-f-e-t-switching': ['transistor', 'gate', 'switch', 'MOSFET'],
  's-r-a-m-cell': ['memory', 'flip-flop', 'cache', 'SRAM'],
  'power-factor': ['AC', 'reactive', 'real power', 'cosine'],
  'tensor-core': ['matrix', 'GPU', 'AI', 'multiply'],
  'systolic-array': ['TPU', 'matrix', 'pipeline', 'parallel'],
  'k-v-cache': ['transformer', 'attention', 'LLM', 'inference'],
  'energy-per-token': ['LLM', 'AI', 'power', 'efficiency'],
  'attention-memory': ['transformer', 'self-attention', 'LLM', 'QKV'],
  'sparsity': ['pruning', 'sparse', 'efficiency', 'zero'],
  'quantization-precision': ['int8', 'fp16', 'model compression', 'bits'],
  'photolithography': ['mask', 'wafer', 'UV', 'pattern'],
  'e-s-d-protection': ['static', 'discharge', 'ESD', 'zap'],
  'electromigration': ['current', 'wire', 'failure', 'atoms'],
  'process-variation': ['manufacturing', 'sigma', 'yield', 'variation'],
};

export const games: { name: string; slug: string; category: string; difficulty: string }[] = [
  // MECHANICS
  { name: 'Center of Mass', slug: 'center-of-mass', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Momentum Conservation', slug: 'momentum-conservation', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Angular Momentum', slug: 'angular-momentum', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Angular Momentum Transfer', slug: 'angular-momentum-transfer', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Projectile Independence', slug: 'projectile-independence', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Torque', slug: 'torque', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Inclined Plane', slug: 'inclined-plane', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Hookes Law', slug: 'hookes-law', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Pendulum Period', slug: 'pendulum-period', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Inertia', slug: 'inertia', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Newtons Third Law', slug: 'newtons-third-law', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Static Kinetic Friction', slug: 'static-kinetic-friction', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Rolling vs Sliding', slug: 'rolling-vs-sliding', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Moment of Inertia', slug: 'moment-of-inertia', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Gyroscopic Precession', slug: 'gyroscopic-precession', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Two Ball Collision', slug: 'two-ball-collision', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Inelastic Collisions', slug: 'inelastic-collisions', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Ballistic Pendulum', slug: 'ballistic-pendulum', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Egg Drop', slug: 'egg-drop', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Buckling', slug: 'buckling', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Orbital Mechanics', slug: 'orbital-mechanics', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Orbital Mechanics Basics', slug: 'orbital-mechanics-basics', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Tidal Forces', slug: 'tidal-forces', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Tidal Locking', slug: 'tidal-locking', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Coriolis Effect', slug: 'coriolis-effect', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Bottle Tornado', slug: 'bottle-tornado', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Brachistochrone', slug: 'brachistochrone', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Brownian Motion', slug: 'brownian-motion', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Cartesian Diver', slug: 'cartesian-diver', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Centripetal Force', slug: 'centripetal-force', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Chain Fountain', slug: 'chain-fountain', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Coupled Pendulums', slug: 'coupled-pendulums', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Cycloid Motion', slug: 'cycloid-motion', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Damped Oscillations', slug: 'damped-oscillations', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Damping', slug: 'damping', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Drag Force', slug: 'drag-force', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Elastic Potential Energy', slug: 'elastic-potential-energy', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Energy Conservation', slug: 'energy-conservation', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Floating Paperclip', slug: 'floating-paperclip', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Forced Oscillations', slug: 'forced-oscillations', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Fracture Mechanics', slug: 'fracture-mechanics', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Gyroscope Stability', slug: 'gyroscope-stability', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Helium Balloon Car', slug: 'helium-balloon-car', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Minimal Surfaces', slug: 'minimal-surfaces', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Non-Newtonian Armor', slug: 'non-newtonian-armor', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Poisson Ratio', slug: 'poisson-ratio', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Precession Nutation', slug: 'precession-nutation', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Rattleback', slug: 'rattleback', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Rolling Race', slug: 'rolling-race', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Sleeping Top', slug: 'sleeping-top', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Stick Slip', slug: 'stick-slip', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Swing Pumping', slug: 'swing-pumping', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Tipping Point', slug: 'tipping-point', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Tuned Mass Damper', slug: 'tuned-mass-damper', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Viscoelasticity', slug: 'viscoelasticity', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Vortex Rings', slug: 'vortex-rings', category: 'mechanics', difficulty: 'intermediate' },
  { name: 'Work Power', slug: 'work-power', category: 'mechanics', difficulty: 'beginner' },
  { name: 'Stable Levitation', slug: 'stable-levitation', category: 'mechanics', difficulty: 'advanced' },
  { name: 'Eddy Current Pendulum', slug: 'eddy-current-pendulum', category: 'mechanics', difficulty: 'intermediate' },

  // THERMODYNAMICS
  { name: 'Thermal Expansion', slug: 'thermal-expansion', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Thermal Contact', slug: 'thermal-contact', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Newton Cooling', slug: 'newton-cooling', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Convection', slug: 'convection', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Convection Currents', slug: 'convection-currents', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Carnot Cycle', slug: 'carnot-cycle', category: 'thermodynamics', difficulty: 'advanced' },
  { name: 'Entropy', slug: 'entropy', category: 'thermodynamics', difficulty: 'advanced' },
  { name: 'Phase Change Energy', slug: 'phase-change-energy', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Latent Heat', slug: 'latent-heat', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Kinetic Theory Gases', slug: 'kinetic-theory-gases', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Gas Laws', slug: 'gas-laws', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Boiling Pressure', slug: 'boiling-pressure', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Evaporative Cooling', slug: 'evaporative-cooling', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Leidenfrost', slug: 'leidenfrost', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Heat Sink Thermal', slug: 'heat-sink-thermal', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Bimetal Thermostat', slug: 'bimetal-thermostat', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Adiabatic Heating', slug: 'adiabatic-heating', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Arrhenius', slug: 'arrhenius', category: 'thermodynamics', difficulty: 'advanced' },
  { name: 'Endothermic Exothermic', slug: 'endothermic-exothermic', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Hand Warmer', slug: 'hand-warmer', category: 'thermodynamics', difficulty: 'beginner' },
  { name: 'Heat Transfer Capacity', slug: 'heat-transfer-capacity', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Infrared Emissivity', slug: 'infrared-emissivity', category: 'thermodynamics', difficulty: 'intermediate' },
  { name: 'Thermal Interface', slug: 'thermal-interface', category: 'thermodynamics', difficulty: 'intermediate' },

  // ELECTROMAGNETISM
  { name: 'Coulombs Law', slug: 'coulombs-law', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Electric Field', slug: 'electric-field', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Electric Field Mapping', slug: 'electric-field-mapping', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Electric Potential', slug: 'electric-potential', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Magnetic Field', slug: 'magnetic-field', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Magnetic Mapping', slug: 'magnetic-mapping', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Electromagnetic Induction', slug: 'electromagnetic-induction', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Electromagnet', slug: 'electromagnet', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Kirchhoffs Laws', slug: 'kirchhoffs-laws', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Circuits', slug: 'circuits', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'RC Time Constant', slug: 'r-c-time-constant', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Transformer', slug: 'transformer', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Classic DC Motor', slug: 'classic-d-c-motor', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Homopolar Motor', slug: 'homopolar-motor', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Oersted Experiment', slug: 'oersted-experiment', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Faraday Cage', slug: 'faraday-cage', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Static Electricity', slug: 'static-electricity', category: 'electromagnetism', difficulty: 'beginner' },
  { name: 'Eddy Currents', slug: 'eddy-currents', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'LC Resonance', slug: 'l-c-resonance', category: 'electromagnetism', difficulty: 'advanced' },
  { name: 'Wireless Charging', slug: 'wireless-charging', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Capacitive Touch', slug: 'capacitive-touch', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Inductive Kickback', slug: 'inductive-kickback', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Galvanic Corrosion', slug: 'galvanic-corrosion', category: 'electromagnetism', difficulty: 'intermediate' },
  { name: 'Humidity ESD', slug: 'humidity-e-s-d', category: 'electromagnetism', difficulty: 'intermediate' },

  // WAVES & OPTICS
  { name: 'Wave Particle Duality', slug: 'wave-particle-duality', category: 'waves', difficulty: 'advanced' },
  { name: 'Wave Interference', slug: 'wave-interference', category: 'waves', difficulty: 'intermediate' },
  { name: 'Wave Speed Tension', slug: 'wave-speed-tension', category: 'waves', difficulty: 'beginner' },
  { name: 'Diffraction', slug: 'diffraction', category: 'waves', difficulty: 'intermediate' },
  { name: 'Diffusion Convection', slug: 'diffusion-convection', category: 'waves', difficulty: 'intermediate' },
  { name: 'Snells Law', slug: 'snells-law', category: 'waves', difficulty: 'beginner' },
  { name: 'Refraction', slug: 'refraction', category: 'waves', difficulty: 'beginner' },
  { name: 'Reflection', slug: 'reflection', category: 'waves', difficulty: 'beginner' },
  { name: 'Law of Reflection', slug: 'law-of-reflection', category: 'waves', difficulty: 'beginner' },
  { name: 'Total Internal Reflection', slug: 'total-internal-reflection', category: 'waves', difficulty: 'intermediate' },
  { name: 'Retroreflection', slug: 'retroreflection', category: 'waves', difficulty: 'intermediate' },
  { name: 'Dispersion', slug: 'dispersion', category: 'waves', difficulty: 'beginner' },
  { name: 'Polarization', slug: 'polarization', category: 'waves', difficulty: 'intermediate' },
  { name: 'Polarized Sky', slug: 'polarized-sky', category: 'waves', difficulty: 'intermediate' },
  { name: 'Doppler Effect', slug: 'doppler-effect', category: 'waves', difficulty: 'intermediate' },
  { name: 'Standing Waves', slug: 'standing-waves', category: 'waves', difficulty: 'intermediate' },
  { name: 'Resonance', slug: 'resonance', category: 'waves', difficulty: 'intermediate' },
  { name: 'Beats', slug: 'beats', category: 'waves', difficulty: 'beginner' },
  { name: 'Speed of Sound', slug: 'speed-of-sound', category: 'waves', difficulty: 'beginner' },
  { name: 'Sound Interference', slug: 'sound-interference', category: 'waves', difficulty: 'intermediate' },
  { name: 'Thin Film Interference', slug: 'thin-film-interference', category: 'waves', difficulty: 'intermediate' },
  { name: 'Laser Speckle', slug: 'laser-speckle', category: 'waves', difficulty: 'advanced' },
  { name: 'Brewster Angle', slug: 'brewster-angle', category: 'waves', difficulty: 'intermediate' },
  { name: 'Camera Obscura', slug: 'camera-obscura', category: 'waves', difficulty: 'beginner' },
  { name: 'Chladni Patterns', slug: 'chladni-patterns', category: 'waves', difficulty: 'intermediate' },
  { name: 'Chromatic Aberration', slug: 'chromatic-aberration', category: 'waves', difficulty: 'intermediate' },
  { name: 'Depth of Field', slug: 'depth-of-field', category: 'waves', difficulty: 'intermediate' },
  { name: 'Echo Time of Flight', slug: 'echo-time-of-flight', category: 'waves', difficulty: 'beginner' },
  { name: 'Fluorescence', slug: 'fluorescence', category: 'waves', difficulty: 'intermediate' },
  { name: 'Fresnel Zones', slug: 'fresnel-zones', category: 'waves', difficulty: 'advanced' },
  { name: 'Lens Focusing', slug: 'lens-focusing', category: 'waves', difficulty: 'beginner' },
  { name: 'Microwave Standing Wave', slug: 'microwave-standing-wave', category: 'waves', difficulty: 'intermediate' },
  { name: 'Moire Patterns', slug: 'moire-patterns', category: 'waves', difficulty: 'intermediate' },
  { name: 'Photoelasticity', slug: 'photoelasticity', category: 'waves', difficulty: 'intermediate' },
  { name: 'Rayleigh Mie Scattering', slug: 'rayleigh-mie-scattering', category: 'waves', difficulty: 'intermediate' },
  { name: 'Reverberation', slug: 'reverberation', category: 'waves', difficulty: 'intermediate' },
  { name: 'Rolling Shutter', slug: 'rolling-shutter', category: 'waves', difficulty: 'intermediate' },
  { name: 'Tape Birefringence', slug: 'tape-birefringence', category: 'waves', difficulty: 'intermediate' },
  { name: 'Wagon Wheel Aliasing', slug: 'wagon-wheel-aliasing', category: 'waves', difficulty: 'intermediate' },
  { name: 'P-Waves S-Waves', slug: 'p-waves-s-waves', category: 'waves', difficulty: 'intermediate' },

  // FLUIDS
  { name: 'Bernoulli', slug: 'bernoulli', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Buoyancy', slug: 'buoyancy', category: 'fluids', difficulty: 'beginner' },
  { name: 'Pascal Law', slug: 'pascal-law', category: 'fluids', difficulty: 'beginner' },
  { name: 'Hydrostatic Pressure', slug: 'hydrostatic-pressure', category: 'fluids', difficulty: 'beginner' },
  { name: 'Venturi Effect', slug: 'venturi-effect', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Capillary Action', slug: 'capillary-action', category: 'fluids', difficulty: 'beginner' },
  { name: 'Viscosity Temperature', slug: 'viscosity-temperature', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Laminar Turbulent', slug: 'laminar-turbulent', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Laminar Flow', slug: 'laminar-flow', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Lift Force', slug: 'lift-force', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Magnus Effect', slug: 'magnus-effect', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Cavitation', slug: 'cavitation', category: 'fluids', difficulty: 'advanced' },
  { name: 'Siphon', slug: 'siphon', category: 'fluids', difficulty: 'beginner' },
  { name: 'Shower Curtain', slug: 'shower-curtain', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Marangoni Tears', slug: 'marangoni-tears', category: 'fluids', difficulty: 'advanced' },
  { name: 'Fluid Inertia', slug: 'fluid-inertia', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Hydraulic Jump', slug: 'hydraulic-jump', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Jar Lid Expansion', slug: 'jar-lid-expansion', category: 'fluids', difficulty: 'beginner' },
  { name: 'Karman Vortex', slug: 'karman-vortex', category: 'fluids', difficulty: 'advanced' },
  { name: 'Pressure Drop', slug: 'pressure-drop', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Shear Thinning', slug: 'shear-thinning', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Supercooling', slug: 'supercooling', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Superhydrophobic', slug: 'superhydrophobic', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Terminal Velocity', slug: 'terminal-velocity', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Water Hammer', slug: 'water-hammer', category: 'fluids', difficulty: 'intermediate' },
  { name: 'Soap Boat', slug: 'soap-boat', category: 'fluids', difficulty: 'beginner' },
  { name: 'Droplet Breakup', slug: 'droplet-breakup', category: 'fluids', difficulty: 'advanced' },

  // MODERN PHYSICS
  { name: 'Photoelectric Effect', slug: 'photoelectric-effect', category: 'modern', difficulty: 'intermediate' },
  { name: 'Molecular Orbitals', slug: 'molecular-orbitals', category: 'modern', difficulty: 'advanced' },
  { name: 'Radiation Effects', slug: 'radiation-effects', category: 'modern', difficulty: 'advanced' },

  // ENGINEERING
  { name: 'MOSFET Switching', slug: 'm-o-s-f-e-t-switching', category: 'engineering', difficulty: 'advanced' },
  { name: 'Solar Cell', slug: 'solar-cell', category: 'engineering', difficulty: 'intermediate' },
  { name: 'LED As Solar Cell', slug: 'l-e-d-as-solar-cell', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Fill Factor', slug: 'fill-factor', category: 'engineering', difficulty: 'advanced' },
  { name: 'Anti Reflective Coating', slug: 'anti-reflective-coating', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Induction Heating', slug: 'induction-heating', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Power Factor', slug: 'power-factor', category: 'engineering', difficulty: 'advanced' },
  { name: 'SRAM Cell', slug: 's-r-a-m-cell', category: 'engineering', difficulty: 'advanced' },
  { name: 'HDD Physics', slug: 'h-d-d-physics', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Liquid Cooling', slug: 'liquid-cooling', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Server Airflow', slug: 'server-airflow', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Antenna Gain', slug: 'antenna-gain', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Antenna Polarization', slug: 'antenna-polarization', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Cable Sizing', slug: 'cable-sizing', category: 'engineering', difficulty: 'intermediate' },
  { name: 'DC-DC Converter', slug: 'd-c-d-c-converter', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Direction Finding', slug: 'direction-finding', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Fan Laws', slug: 'fan-laws', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Generator Startup', slug: 'generator-startup', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Grid Frequency', slug: 'grid-frequency', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Ground Fault', slug: 'ground-fault', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Inverter Sine Wave', slug: 'inverter-sine-wave', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Link Budget', slug: 'link-budget', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Network Congestion', slug: 'network-congestion', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Power Delivery Network', slug: 'power-delivery-network', category: 'engineering', difficulty: 'advanced' },
  { name: 'Power Loss', slug: 'power-loss', category: 'engineering', difficulty: 'intermediate' },
  { name: 'UPS Battery Sizing', slug: 'u-p-s-battery-sizing', category: 'engineering', difficulty: 'intermediate' },
  { name: 'UPS Efficiency', slug: 'u-p-s-efficiency', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Thermal Throttling', slug: 'thermal-throttling', category: 'engineering', difficulty: 'intermediate' },
  { name: 'PUE Calculator', slug: 'p-u-e-calculator', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Microphone', slug: 'microphone', category: 'engineering', difficulty: 'beginner' },
  { name: 'Make Microphone', slug: 'make-microphone', category: 'engineering', difficulty: 'beginner' },
  { name: 'Speaker Principle', slug: 'speaker-principle', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Straw Instrument', slug: 'straw-instrument', category: 'engineering', difficulty: 'beginner' },
  { name: 'String Sizing', slug: 'string-sizing', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Metronome Sync', slug: 'metronome-sync', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Phone Seismometer', slug: 'phone-seismometer', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Reaction Time', slug: 'reaction-time', category: 'engineering', difficulty: 'beginner' },
  { name: 'Cloud In Bottle', slug: 'cloud-in-bottle', category: 'engineering', difficulty: 'beginner' },
  { name: 'Battery Internal Resistance', slug: 'battery-internal-resistance', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Fiber Signal Loss', slug: 'fiber-signal-loss', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Noise Margin', slug: 'noise-margin', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Transmission Line', slug: 'transmission-line', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Crosstalk', slug: 'crosstalk', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Chiller COP', slug: 'chiller-c-o-p', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Satellite Doppler', slug: 'satellite-doppler', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Satellite Solar Angle', slug: 'satellite-solar-angle', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Satellite Thermal', slug: 'satellite-thermal', category: 'engineering', difficulty: 'intermediate' },
  { name: 'Space Radiation', slug: 'space-radiation', category: 'engineering', difficulty: 'advanced' },

  // COMPUTING & AI
  { name: 'GPU Power States', slug: 'g-p-u-power-states', category: 'computing', difficulty: 'intermediate' },
  { name: 'GPU Memory Bandwidth', slug: 'g-p-u-memory-bandwidth', category: 'computing', difficulty: 'intermediate' },
  { name: 'GPU Occupancy', slug: 'g-p-u-occupancy', category: 'computing', difficulty: 'advanced' },
  { name: 'TPU vs GPU', slug: 't-p-uvs-g-p-u', category: 'computing', difficulty: 'intermediate' },
  { name: 'ASIC vs GPU', slug: 'a-s-i-cvs-g-p-u', category: 'computing', difficulty: 'intermediate' },
  { name: 'Tensor Core', slug: 'tensor-core', category: 'computing', difficulty: 'advanced' },
  { name: 'Systolic Array', slug: 'systolic-array', category: 'computing', difficulty: 'advanced' },
  { name: 'Memory Hierarchy', slug: 'memory-hierarchy', category: 'computing', difficulty: 'intermediate' },
  { name: 'Network Latency', slug: 'network-latency', category: 'computing', difficulty: 'intermediate' },
  { name: 'AI Inference Latency', slug: 'a-i-inference-latency', category: 'computing', difficulty: 'advanced' },
  { name: 'Energy Per Token', slug: 'energy-per-token', category: 'computing', difficulty: 'advanced' },
  { name: 'PCIe Bandwidth', slug: 'p-c-ie-bandwidth', category: 'computing', difficulty: 'intermediate' },
  { name: 'ECC Memory', slug: 'e-c-c-memory', category: 'computing', difficulty: 'intermediate' },
  { name: 'DRAM Refresh', slug: 'd-r-a-m-refresh', category: 'computing', difficulty: 'intermediate' },
  { name: 'DVFS', slug: 'd-v-f-s', category: 'computing', difficulty: 'intermediate' },
  { name: 'KV Cache', slug: 'k-v-cache', category: 'computing', difficulty: 'advanced' },
  { name: 'Data Movement Energy', slug: 'data-movement-energy', category: 'computing', difficulty: 'intermediate' },
  { name: 'Batching Latency', slug: 'batching-latency', category: 'computing', difficulty: 'intermediate' },
  { name: 'Attention Memory', slug: 'attention-memory', category: 'computing', difficulty: 'intermediate' },
  { name: 'Attention Loves Bandwidth', slug: 'attention-loves-bandwidth', category: 'computing', difficulty: 'intermediate' },
  { name: 'Sparsity', slug: 'sparsity', category: 'computing', difficulty: 'intermediate' },
  { name: 'Quantization Precision', slug: 'quantization-precision', category: 'computing', difficulty: 'intermediate' },
  { name: 'LLM to SPICE', slug: 'l-l-m-to-s-p-i-c-e', category: 'computing', difficulty: 'advanced' },
  { name: 'Ask for Assumptions', slug: 'ask-for-assumptions', category: 'computing', difficulty: 'beginner' },
  { name: 'Model as Reviewer', slug: 'model-as-reviewer', category: 'computing', difficulty: 'intermediate' },
  { name: 'Patch Discipline', slug: 'patch-discipline', category: 'computing', difficulty: 'intermediate' },
  { name: 'Prompt Injection Safety', slug: 'prompt-injection-safety', category: 'computing', difficulty: 'intermediate' },
  { name: 'Spec First Prompting', slug: 'spec-first-prompting', category: 'computing', difficulty: 'intermediate' },
  { name: 'Test First Prompting', slug: 'test-first-prompting', category: 'computing', difficulty: 'intermediate' },
  { name: 'Tool Aware Prompting', slug: 'tool-aware-prompting', category: 'computing', difficulty: 'intermediate' },
  { name: 'Verification Harness', slug: 'verification-harness', category: 'computing', difficulty: 'intermediate' },
  { name: 'Remote Game', slug: 'remote-game', category: 'computing', difficulty: 'intermediate' },
  { name: 'Manufacturing Drives Architecture', slug: 'manufacturing-drives-architecture', category: 'computing', difficulty: 'advanced' },

  // SEMICONDUCTOR
  { name: 'CMP Planarization', slug: 'c-m-p-planarization', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Cleanroom Yield', slug: 'cleanroom-yield', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Clock Distribution', slug: 'clock-distribution', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Clock Jitter', slug: 'clock-jitter', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Decoupling Capacitor', slug: 'decoupling-capacitor', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Deposition Types', slug: 'deposition-types', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Design to Fab Translation', slug: 'design-to-fab-translation', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Doping Diffusion', slug: 'doping-diffusion', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Electromigration', slug: 'electromigration', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'EMI Shielding', slug: 'e-m-i-shielding', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'ESD Protection', slug: 'e-s-d-protection', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Etch Anisotropy', slug: 'etch-anisotropy', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Flip Chip Wirebond', slug: 'flip-chip-wirebond', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Ground Bounce', slug: 'ground-bounce', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Interconnect Topology', slug: 'interconnect-topology', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Ion Implantation', slug: 'ion-implantation', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'IR Drop', slug: 'i-r-drop', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Leakage Current', slug: 'leakage-current', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Leakage Power', slug: 'leakage-power', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Litho Focus Dose', slug: 'litho-focus-dose', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Metastability', slug: 'metastability', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Overlay Error', slug: 'overlay-error', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Photolithography', slug: 'photolithography', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'Process Variation', slug: 'process-variation', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'RC Delay', slug: 'r-c-delay', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'RC Delay Interconnect', slug: 'r-c-delay-interconnect', category: 'semiconductor', difficulty: 'intermediate' },
  { name: 'SRAM Yield Redundancy', slug: 's-r-a-m-yield-redundancy', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Chiplet Architecture', slug: 'chiplet-architecture', category: 'semiconductor', difficulty: 'advanced' },
  { name: 'Chiplets vs Monoliths', slug: 'chiplets-vs-monoliths', category: 'semiconductor', difficulty: 'intermediate' },

  // SOLAR & PV
  { name: 'Bifacial Albedo', slug: 'bifacial-albedo', category: 'solar', difficulty: 'intermediate' },
  { name: 'Bypass Diodes', slug: 'bypass-diodes', category: 'solar', difficulty: 'intermediate' },
  { name: 'Cell to Module Losses', slug: 'cell-to-module-losses', category: 'solar', difficulty: 'intermediate' },
  { name: 'Encapsulation UV Aging', slug: 'encapsulation-u-v-aging', category: 'solar', difficulty: 'intermediate' },
  { name: 'Hotspots', slug: 'hotspots', category: 'solar', difficulty: 'intermediate' },
  { name: 'MPPT', slug: 'm-p-p-t', category: 'solar', difficulty: 'intermediate' },
  { name: 'Passivation Recombination', slug: 'passivation-recombination', category: 'solar', difficulty: 'advanced' },
  { name: 'PV IV Curve', slug: 'p-v-i-v-curve', category: 'solar', difficulty: 'intermediate' },
  { name: 'Screen Printing Metallization', slug: 'screen-printing-metallization', category: 'solar', difficulty: 'intermediate' },
  { name: 'Series Parallel PV', slug: 'series-parallel-p-v', category: 'solar', difficulty: 'intermediate' },
  { name: 'Shunt Series Defects', slug: 'shunt-series-defects', category: 'solar', difficulty: 'intermediate' },
  { name: 'Silicon Texturing', slug: 'silicon-texturing', category: 'solar', difficulty: 'intermediate' },
  { name: 'Solar Temp Coefficient', slug: 'solar-temp-coefficient', category: 'solar', difficulty: 'intermediate' },
  { name: 'Solar Thermal Derating', slug: 'solar-thermal-derating', category: 'solar', difficulty: 'intermediate' },
  { name: 'Solar vs IC Purity', slug: 'solar-vs-i-c-purity', category: 'solar', difficulty: 'intermediate' },
  { name: 'Solar Yield Prediction', slug: 'solar-yield-prediction', category: 'solar', difficulty: 'intermediate' },
  { name: 'Spectral Mismatch', slug: 'spectral-mismatch', category: 'solar', difficulty: 'intermediate' },
  { name: 'Texturing vs Lithography', slug: 'texturing-vs-lithography', category: 'solar', difficulty: 'intermediate' },

  // ELON GAMES
  { name: 'ELON Constraint Cascade', slug: 'e-l-o-n_-constraint-cascade', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Precision Budget', slug: 'e-l-o-n_-precision-budget', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Grid Balance', slug: 'e-l-o-n_-grid-balance', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Transformer Timeline', slug: 'e-l-o-n_-transformer-timeline', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Interconnect Queue', slug: 'e-l-o-n_-interconnect-queue', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Power Plant Picker', slug: 'e-l-o-n_-power-plant-picker', category: 'elon', difficulty: 'beginner' },
  { name: 'ELON Fuel Delivery', slug: 'e-l-o-n_-fuel-delivery', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Blade Factory', slug: 'e-l-o-n_-blade-factory', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Facility Power', slug: 'e-l-o-n_-facility-power', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Cooling Strategy', slug: 'e-l-o-n_-cooling-strategy', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Uptime Architect', slug: 'e-l-o-n_-uptime-architect', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Solar Manufacturing', slug: 'e-l-o-n_-solar-manufacturing', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Solar Deployment', slug: 'e-l-o-n_-solar-deployment', category: 'elon', difficulty: 'beginner' },
  { name: 'ELON Battery System', slug: 'e-l-o-n_-battery-system', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Ore To Metal', slug: 'e-l-o-n_-ore-to-metal', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Mining Bottleneck', slug: 'e-l-o-n_-mining-bottleneck', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Critical Minerals', slug: 'e-l-o-n_-critical-minerals', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Fab Yield Curve', slug: 'e-l-o-n_-fab-yield-curve', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Chip Supply Web', slug: 'e-l-o-n_-chip-supply-web', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Packaging Limit', slug: 'e-l-o-n_-packaging-limit', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Cluster Comms', slug: 'e-l-o-n_-cluster-comms', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Optical Link', slug: 'e-l-o-n_-optical-link', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Space Comms', slug: 'e-l-o-n_-space-comms', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Orbit Designer', slug: 'e-l-o-n_-orbit-designer', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Radiation Armor', slug: 'e-l-o-n_-radiation-armor', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Space Radiator', slug: 'e-l-o-n_-space-radiator', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Orbital Factory', slug: 'e-l-o-n_-orbital-factory', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Rocket Materials', slug: 'e-l-o-n_-rocket-materials', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON TPS Turnaround', slug: 'e-l-o-n_-t-p-s-turnaround', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Actuator Limits', slug: 'e-l-o-n_-actuator-limits', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Robot Learning', slug: 'e-l-o-n_-robot-learning', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Recursive Bot', slug: 'e-l-o-n_-recursive-bot', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Throughput Cadence', slug: 'e-l-o-n_-throughput-cadence', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Capital Stack', slug: 'e-l-o-n_-capital-stack', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Policy Risk', slug: 'e-l-o-n_-policy-risk', category: 'elon', difficulty: 'intermediate' },
  { name: 'ELON Gigawatt Blueprint', slug: 'e-l-o-n_-gigawatt-blueprint', category: 'elon', difficulty: 'advanced' },
  { name: 'ELON Power Plant Picker', slug: 'e-l-o-n_-power-plant-picker', category: 'elon', difficulty: 'beginner' },
];

// Simple fuzzy match: checks if all characters of query appear in order in target
export function fuzzyMatch(query: string, target: string): number {
  const q = query.toLowerCase();
  const t = target.toLowerCase();
  if (t.includes(q)) return 100;
  const words = t.split(/[\s\-_]+/);
  const initials = words.map(w => w[0] || '').join('').toLowerCase();
  if (initials.includes(q)) return 80;
  let qi = 0;
  for (let ti = 0; ti < t.length && qi < q.length; ti++) {
    if (t[ti] === q[qi]) qi++;
  }
  if (qi === q.length) return 50;
  return 0;
}

// Deduplicated games list
const _uniqueGames = (() => {
  const seen = new Set<string>();
  return games.filter(g => {
    if (seen.has(g.slug)) return false;
    seen.add(g.slug);
    return true;
  });
})();

export function getUniqueGames() {
  return _uniqueGames;
}

/** Search games by query, returning top `limit` matches scored by relevance. */
export function searchGames(query: string, limit = 8): typeof games {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored = _uniqueGames.map(game => {
    const cat = gameCategories[game.category as GameCategoryKey];
    const tags = searchTags[game.slug] || [];
    const tagString = tags.join(' ').toLowerCase();
    const decodedSlug = game.slug.replace(/-/g, '').toLowerCase();

    let score = 0;
    if (game.name.toLowerCase() === q) score = 1000;
    else if (game.name.toLowerCase().startsWith(q)) score = 500;
    else if (game.name.toLowerCase().includes(q)) score = 400;
    else if (decodedSlug.includes(q.replace(/[\s\-]/g, ''))) score = 350;
    else if (tags.some(t => t.toLowerCase() === q)) score = 300;
    else if (tagString.includes(q)) score = 250;
    else if (cat && cat.name.toLowerCase().includes(q)) score = 200;
    else if (cat && cat.description.toLowerCase().includes(q)) score = 150;
    else {
      const fs = fuzzyMatch(q, game.name);
      if (fs > 0) score = fs;
    }

    return { game, score };
  })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score || a.game.name.localeCompare(b.game.name));

  return scored.slice(0, limit).map(s => s.game);
}
