/**
 * GAME SEO DATA — Per-game metadata optimized for search engine visibility.
 *
 * Each entry provides a meta title, description, concept tags, difficulty,
 * estimated completion time, and FAQ items for structured data (JSON-LD).
 * Covers 50+ of the most important game modules across all categories.
 */

// ============================================================
// TYPES
// ============================================================

export interface GameSEOFAQ {
  question: string;
  answer: string;
}

export interface GameSEOEntry {
  metaTitle: string;
  metaDescription: string;
  concepts: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedMinutes: number;
  faqItems: GameSEOFAQ[];
}

// ============================================================
// DATA — keyed by game slug (as generated by pascalToSlug)
// ============================================================

export const gameSEOData: Record<string, GameSEOEntry> = {

  // ================================================================
  // CLASSICAL MECHANICS
  // ================================================================

  'newtons-third-law': {
    metaTitle: 'Newton\'s Third Law - Interactive Simulator | Atlas Coach',
    metaDescription: 'Explore Newton\'s Third Law with an interactive simulator. Push objects, observe equal and opposite reaction forces, and build intuition for action-reaction pairs in real time.',
    concepts: ['Newton\'s third law', 'action-reaction pairs', 'force', 'contact forces'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'What is Newton\'s Third Law?', answer: 'For every action force, there is an equal and opposite reaction force. When you push a wall, the wall pushes back on you with the same magnitude.' },
      { question: 'Why don\'t action-reaction forces cancel out?', answer: 'They act on different objects. You push the wall (force on wall) and the wall pushes you (force on you). Since they act on different bodies, they do not cancel.' },
    ],
  },

  'momentum-conservation': {
    metaTitle: 'Conservation of Momentum - Interactive Simulator | Atlas Coach',
    metaDescription: 'Visualize momentum conservation in collisions. Adjust masses and velocities, watch elastic and inelastic impacts, and verify that total momentum is always conserved.',
    concepts: ['momentum', 'conservation law', 'collision', 'impulse'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is conservation of momentum?', answer: 'In an isolated system with no external forces, total momentum before a collision equals total momentum after. This holds for both elastic and inelastic collisions.' },
      { question: 'Does momentum conservation apply to explosions?', answer: 'Yes. An explosion is a collision in reverse. Total momentum of all fragments after the explosion equals total momentum before (usually zero for a stationary object).' },
    ],
  },

  'centripetal-force': {
    metaTitle: 'Centripetal Force - Interactive Simulator | Atlas Coach',
    metaDescription: 'Discover centripetal force with hands-on simulation. Swing objects in circles, adjust radius and speed, and see how the required inward force changes in real time.',
    concepts: ['centripetal force', 'circular motion', 'centripetal acceleration', 'angular velocity'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'What provides centripetal force?', answer: 'Different forces can serve as centripetal force: gravity for orbits, tension for a ball on a string, friction for a car turning, or normal force in a roller coaster loop.' },
      { question: 'Is centrifugal force real?', answer: 'Centrifugal force is a fictitious force that appears only in rotating reference frames. In an inertial frame, the only real force is centripetal (inward).' },
    ],
  },

  'energy-conservation': {
    metaTitle: 'Energy Conservation - Interactive Simulator | Atlas Coach',
    metaDescription: 'Watch kinetic and potential energy transform in real time. Launch objects, track energy bar charts, and prove that total mechanical energy is conserved without friction.',
    concepts: ['kinetic energy', 'potential energy', 'conservation of energy', 'work-energy theorem'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'Can energy be created or destroyed?', answer: 'No. The first law of thermodynamics states energy is always conserved. It transforms between forms (kinetic, potential, thermal) but the total never changes.' },
      { question: 'Where does energy go when friction is present?', answer: 'Friction converts mechanical energy into thermal energy (heat). Total energy is still conserved, but mechanical energy available for motion decreases.' },
    ],
  },

  'static-kinetic-friction': {
    metaTitle: 'Static vs Kinetic Friction - Interactive Simulator | Atlas Coach',
    metaDescription: 'Compare static and kinetic friction in this interactive simulator. Apply increasing force, observe the breakaway point, and measure both friction coefficients.',
    concepts: ['static friction', 'kinetic friction', 'friction coefficient', 'normal force'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why is static friction greater than kinetic friction?', answer: 'At rest, surface asperities interlock and form micro-bonds. Once sliding begins, contacts are more transient, reducing the average friction force by 10-30%.' },
      { question: 'Does friction depend on surface area?', answer: 'For idealized rigid surfaces, no (Amontons\' law). In practice, deformable materials like rubber show some area dependence due to adhesion effects.' },
    ],
  },

  'angular-momentum': {
    metaTitle: 'Angular Momentum - Interactive Simulator | Atlas Coach',
    metaDescription: 'Explore angular momentum conservation with spinning objects. Change moment of inertia and watch rotation speed change, like a figure skater pulling in their arms.',
    concepts: ['angular momentum', 'moment of inertia', 'conservation of angular momentum', 'torque'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why does a skater spin faster when pulling in their arms?', answer: 'Angular momentum L = I*omega is conserved. Reducing I (pulling arms in) forces omega to increase proportionally.' },
      { question: 'What is the angular momentum of the Earth?', answer: 'About 7.1 x 10^33 kg*m^2/s from rotation alone. This is why Earth\'s rotation changes extremely slowly over millions of years (tidal deceleration).' },
    ],
  },

  'terminal-velocity': {
    metaTitle: 'Terminal Velocity - Interactive Simulator | Atlas Coach',
    metaDescription: 'Simulate terminal velocity for different objects. Adjust mass, area, and drag coefficient to find the speed where gravitational force equals air resistance.',
    concepts: ['terminal velocity', 'drag force', 'air resistance', 'free fall'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is the terminal velocity of a skydiver?', answer: 'About 55 m/s (120 mph) belly-down. In a head-down dive, it reaches 75 m/s (170 mph) due to reduced cross-sectional area.' },
      { question: 'Does terminal velocity depend on mass?', answer: 'Yes. Heavier objects need more drag force (thus more speed) to balance their greater weight. A bowling ball has a higher terminal velocity than a tennis ball.' },
    ],
  },

  // ================================================================
  // OSCILLATIONS & WAVES
  // ================================================================

  'pendulum-period': {
    metaTitle: 'Pendulum Period - Interactive Simulator | Atlas Coach',
    metaDescription: 'Measure pendulum period as a function of length and gravity. Verify that period depends on length but not mass, and explore the small-angle approximation limits.',
    concepts: ['simple harmonic motion', 'pendulum period', 'small angle approximation', 'gravity'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'Why doesn\'t pendulum period depend on mass?', answer: 'Both gravitational force and inertia are proportional to mass. The mass cancels in the equation of motion, giving T = 2pi*sqrt(L/g).' },
      { question: 'How accurate is the small-angle approximation?', answer: 'For amplitudes below 15 degrees, the error is under 0.5%. At 30 degrees, it is about 2%. At 90 degrees, the period is 18% longer than the simple formula predicts.' },
    ],
  },

  'resonance': {
    metaTitle: 'Resonance - Interactive Simulator | Atlas Coach',
    metaDescription: 'Drive an oscillator at different frequencies and watch amplitude peak at resonance. Adjust damping, measure Q factor, and understand frequency response curves.',
    concepts: ['resonance', 'natural frequency', 'Q factor', 'forced oscillation', 'damping'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What determines the resonant frequency?', answer: 'For a spring-mass system, f = 1/(2pi)*sqrt(k/m). For an LC circuit, f = 1/(2pi*sqrt(LC)). Resonant frequency depends on the system\'s stiffness and inertia.' },
      { question: 'What is the Q factor?', answer: 'Q = f_resonance / bandwidth. It measures how sharply peaked the resonance is. A tuning fork (Q ~ 1000) rings for seconds; a drum (Q ~ 10) dies quickly.' },
    ],
  },

  'doppler-effect': {
    metaTitle: 'Doppler Effect - Interactive Simulator | Atlas Coach',
    metaDescription: 'Hear and see the Doppler effect in action. Move a sound source, observe frequency shifts, and learn how radar guns, ultrasound, and redshift work.',
    concepts: ['Doppler effect', 'frequency shift', 'wavelength compression', 'sonic boom'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Does the Doppler effect work with light?', answer: 'Yes. Approaching objects are blue-shifted (higher frequency) and receding objects are red-shifted. Astronomers use this to measure galaxy velocities and confirm the expanding universe.' },
      { question: 'What causes a sonic boom?', answer: 'When a source exceeds the speed of sound, pressure waves pile up into a Mach cone. The concentrated wavefront reaches an observer as a sharp bang.' },
    ],
  },

  'standing-waves': {
    metaTitle: 'Standing Waves - Interactive Simulator | Atlas Coach',
    metaDescription: 'Create standing waves on a virtual string. Find harmonics, visualize nodes and antinodes, and understand how musical instruments produce specific pitches.',
    concepts: ['standing waves', 'harmonics', 'nodes', 'antinodes', 'resonant frequencies'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is the difference between a node and an antinode?', answer: 'A node is a point of zero displacement that never moves. An antinode is a point of maximum displacement. They alternate, spaced a quarter wavelength apart.' },
      { question: 'Why can only certain frequencies form standing waves?', answer: 'Boundary conditions (fixed ends of a string) require an integer number of half-wavelengths to fit the length. Only discrete frequencies satisfy this, creating the harmonic series.' },
    ],
  },

  // ================================================================
  // FLUID MECHANICS
  // ================================================================

  'bernoulli': {
    metaTitle: 'Bernoulli\'s Principle - Interactive Simulator | Atlas Coach',
    metaDescription: 'Simulate fluid flow through pipes and measure pressure changes. Visualize Bernoulli\'s equation in action and understand why fast-moving fluids have low pressure.',
    concepts: ['Bernoulli\'s principle', 'fluid pressure', 'continuity equation', 'dynamic pressure'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is Bernoulli\'s equation?', answer: 'P + 1/2*rho*v^2 + rho*g*h = constant along a streamline. It expresses conservation of energy for ideal fluid flow.' },
      { question: 'Why does a curveball curve?', answer: 'Spin creates faster airflow on one side (lower pressure) and slower on the other (higher pressure). The net pressure difference pushes the ball sideways.' },
    ],
  },

  'laminar-turbulent': {
    metaTitle: 'Laminar vs Turbulent Flow - Interactive Simulator | Atlas Coach',
    metaDescription: 'Watch the transition from laminar to turbulent flow in real time. Calculate Reynolds numbers and learn when smooth flow breaks down into chaotic turbulence.',
    concepts: ['laminar flow', 'turbulent flow', 'Reynolds number', 'flow transition', 'viscosity'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What Reynolds number marks the transition?', answer: 'In a pipe, laminar flow occurs below Re of about 2300. Above Re of about 4000, flow is fully turbulent. The transition region between is unpredictable.' },
      { question: 'Is turbulent flow always undesirable?', answer: 'No. Turbulence enhances mixing and heat transfer. Heat exchangers and combustion chambers are deliberately designed to promote turbulence.' },
    ],
  },

  'buoyancy': {
    metaTitle: 'Buoyancy & Archimedes Principle - Interactive Simulator | Atlas Coach',
    metaDescription: 'Submerge objects of different densities and watch buoyant forces act. Verify Archimedes\' principle by comparing displaced water weight to the measured buoyant force.',
    concepts: ['buoyancy', 'Archimedes\' principle', 'density', 'displaced volume', 'floating'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'What determines if an object floats or sinks?', answer: 'An object floats if its average density is less than the fluid density. A steel ship floats because its average density (including air inside) is less than water.' },
      { question: 'Does shape affect buoyancy?', answer: 'Shape does not change the buoyant force on a fully submerged object (only displaced volume matters). But shape determines stability and whether the object capsizes.' },
    ],
  },

  'venturi-effect': {
    metaTitle: 'Venturi Effect - Interactive Simulator | Atlas Coach',
    metaDescription: 'Simulate flow through a Venturi tube. Measure pressure drops at the throat, calculate flow rates, and see how carburetors and aspirators work.',
    concepts: ['Venturi effect', 'continuity equation', 'pressure drop', 'flow measurement'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'How does a Venturi meter measure flow?', answer: 'By measuring the pressure difference between the wide and narrow sections. Flow rate is calculated from Bernoulli\'s equation and the continuity equation.' },
      { question: 'Can a Venturi create suction?', answer: 'Yes. At high flow speeds, throat pressure drops below atmospheric, creating vacuum. This is the operating principle of Venturi aspirators and ejector pumps.' },
    ],
  },

  'hydraulic-jump': {
    metaTitle: 'Hydraulic Jump - Interactive Simulator | Atlas Coach',
    metaDescription: 'Observe the dramatic transition from supercritical to subcritical flow. Adjust Froude number and channel geometry to control the hydraulic jump position.',
    concepts: ['hydraulic jump', 'Froude number', 'supercritical flow', 'energy dissipation'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is a hydraulic jump?', answer: 'An abrupt transition from fast, shallow (supercritical) flow to slow, deep (subcritical) flow. It dissipates kinetic energy through turbulence and is analogous to a shock wave.' },
      { question: 'Where can I see a hydraulic jump?', answer: 'In your kitchen sink where tap water hits the flat surface and forms a circular ring. Also in dam spillways, river rapids, and tidal bores.' },
    ],
  },

  // ================================================================
  // THERMODYNAMICS
  // ================================================================

  'carnot-cycle': {
    metaTitle: 'Carnot Cycle - Interactive Simulator | Atlas Coach',
    metaDescription: 'Trace the Carnot cycle on PV and TS diagrams. Adjust reservoir temperatures to see maximum theoretical efficiency change. Understand the second law of thermodynamics.',
    concepts: ['Carnot cycle', 'thermodynamic efficiency', 'isothermal process', 'adiabatic process'],
    difficulty: 'advanced',
    estimatedMinutes: 12,
    faqItems: [
      { question: 'What is the Carnot efficiency formula?', answer: 'eta = 1 - T_cold/T_hot (in Kelvin). A power plant with 600K hot and 300K cold reservoirs has a maximum possible efficiency of 50%.' },
      { question: 'Why is the Carnot cycle important?', answer: 'It sets the absolute upper limit on efficiency for any heat engine between two temperatures. No real engine can exceed this, per the second law of thermodynamics.' },
    ],
  },

  'thermal-expansion': {
    metaTitle: 'Thermal Expansion - Interactive Simulator | Atlas Coach',
    metaDescription: 'Heat different materials and measure their expansion. Compare expansion coefficients, explore bimetallic strips, and learn why bridges need expansion joints.',
    concepts: ['thermal expansion', 'linear expansion coefficient', 'bimetallic strip', 'thermal stress'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'Which material expands the most?', answer: 'Among common materials, aluminum (alpha = 23e-6/K) expands about twice as much as steel (12e-6/K). Polymers expand even more, at 50-200e-6/K.' },
      { question: 'What is a bimetallic strip?', answer: 'Two metals with different expansion coefficients bonded together. Differential expansion causes bending when heated, used in thermostats, circuit breakers, and toasters.' },
    ],
  },

  'entropy': {
    metaTitle: 'Entropy - Interactive Simulator | Atlas Coach',
    metaDescription: 'Visualize entropy and the second law of thermodynamics. Watch ordered states evolve into disorder and understand why some processes are inherently irreversible.',
    concepts: ['entropy', 'second law of thermodynamics', 'disorder', 'irreversibility', 'microstates'],
    difficulty: 'advanced',
    estimatedMinutes: 12,
    faqItems: [
      { question: 'What is entropy in simple terms?', answer: 'Entropy measures the number of microscopic arrangements consistent with a macroscopic state. Higher entropy = more possible arrangements = more likely state.' },
      { question: 'Can entropy decrease locally?', answer: 'Yes, but only by increasing entropy elsewhere by a greater amount. A refrigerator decreases entropy inside by generating more entropy in the room via its compressor motor.' },
    ],
  },

  'leidenfrost': {
    metaTitle: 'Leidenfrost Effect - Interactive Simulator | Atlas Coach',
    metaDescription: 'Drop water on a virtual hot surface and watch the Leidenfrost effect. Explore the boiling curve, find the Leidenfrost point, and understand vapor film insulation.',
    concepts: ['Leidenfrost effect', 'film boiling', 'nucleate boiling', 'vapor cushion', 'boiling curve'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'At what temperature does the Leidenfrost effect occur?', answer: 'For water on stainless steel, about 200C (390F). Above this, drops levitate on a vapor cushion and paradoxically evaporate much more slowly than at lower temperatures.' },
      { question: 'Is the Leidenfrost effect why hot coal walking works?', answer: 'Partially. Moisture on feet creates a brief vapor barrier. But low thermal conductivity of charcoal, brief contact time, and foot calluses are the main protective factors.' },
    ],
  },

  // ================================================================
  // ELECTRICITY & MAGNETISM
  // ================================================================

  'coulombs-law': {
    metaTitle: 'Coulomb\'s Law - Interactive Simulator | Atlas Coach',
    metaDescription: 'Place electric charges and watch forces appear in real time. Verify the inverse-square law, explore superposition, and build intuition for electrostatic interactions.',
    concepts: ['Coulomb\'s law', 'electric force', 'inverse-square law', 'charge', 'superposition'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'How does Coulomb\'s law compare to gravity?', answer: 'Both follow inverse-square laws. But electric forces are about 10^36 times stronger than gravity between fundamental particles. Gravity dominates at large scales only because matter is electrically neutral overall.' },
      { question: 'Why don\'t protons in a nucleus repel apart?', answer: 'The strong nuclear force, operating at subatomic distances, is about 100x stronger than electromagnetic repulsion, holding the nucleus together.' },
    ],
  },

  'kirchhoffs-laws': {
    metaTitle: 'Kirchhoff\'s Laws - Interactive Circuit Simulator | Atlas Coach',
    metaDescription: 'Build circuits and verify Kirchhoff\'s current and voltage laws. Add resistors, batteries, and junctions, then trace current and voltage around any loop.',
    concepts: ['KCL', 'KVL', 'circuit analysis', 'node equations', 'loop equations'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What are Kirchhoff\'s two laws?', answer: 'KCL: total current entering a node equals total current leaving (charge conservation). KVL: voltages around any closed loop sum to zero (energy conservation).' },
      { question: 'When should I use mesh vs nodal analysis?', answer: 'Mesh analysis for circuits with fewer loops than nodes. Nodal analysis when nodes are fewer. Both yield the same results; choose whichever produces fewer simultaneous equations.' },
    ],
  },

  'electromagnetic-induction': {
    metaTitle: 'Electromagnetic Induction - Interactive Simulator | Atlas Coach',
    metaDescription: 'Move magnets through coils and generate electricity. Visualize Faraday\'s law, observe Lenz\'s law in action, and understand how generators and transformers work.',
    concepts: ['Faraday\'s law', 'electromagnetic induction', 'Lenz\'s law', 'magnetic flux', 'EMF'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is Faraday\'s law?', answer: 'A changing magnetic flux through a loop induces an EMF: EMF = -d(Phi)/dt. Faster flux change produces larger voltage. This is how all generators work.' },
      { question: 'What is Lenz\'s law?', answer: 'Induced current flows in the direction that opposes the flux change causing it. This is why a magnet falls slowly through a copper tube: eddy currents create an opposing field.' },
    ],
  },

  'faraday-cage': {
    metaTitle: 'Faraday Cage - Interactive Simulator | Atlas Coach',
    metaDescription: 'Build a Faraday cage and test electromagnetic shielding. Vary mesh size, material conductivity, and signal frequency to see how shielding effectiveness changes.',
    concepts: ['Faraday cage', 'electromagnetic shielding', 'charge redistribution', 'skin depth'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'How does a Faraday cage work?', answer: 'External fields cause charges on the cage to redistribute, creating an equal and opposite internal field. The net field inside is zero for electrostatic fields and strongly attenuated for RF.' },
      { question: 'Can a Faraday cage block all frequencies?', answer: 'A solid conductor blocks all EM frequencies. A mesh blocks wavelengths larger than the openings. Your microwave door blocks 2.45 GHz microwaves but passes visible light.' },
    ],
  },

  // ================================================================
  // OPTICS
  // ================================================================

  'snells-law': {
    metaTitle: 'Snell\'s Law - Interactive Simulator | Atlas Coach',
    metaDescription: 'Bend light rays at material boundaries. Adjust refractive indices, measure incidence and refraction angles, and discover the critical angle for total internal reflection.',
    concepts: ['Snell\'s law', 'refraction', 'refractive index', 'critical angle', 'total internal reflection'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'What is Snell\'s law?', answer: 'n1*sin(theta1) = n2*sin(theta2). It relates angles and refractive indices at a boundary. Light bends toward the normal when entering a denser medium.' },
      { question: 'What is the critical angle?', answer: 'The incidence angle above which total internal reflection occurs. For glass to air: arcsin(1/1.5) = 42 degrees. Beyond this, all light reflects back into the glass.' },
    ],
  },

  'diffraction': {
    metaTitle: 'Diffraction - Interactive Simulator | Atlas Coach',
    metaDescription: 'Pass light through slits and observe diffraction patterns. Adjust wavelength and slit width to explore single-slit, double-slit, and grating diffraction.',
    concepts: ['diffraction', 'single slit', 'double slit', 'diffraction grating', 'interference'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why does diffraction happen?', answer: 'Each point on a wavefront acts as a new source (Huygens\' principle). At an opening, unblocked wavelets spread and interfere, creating the diffraction pattern.' },
      { question: 'What is the difference between diffraction and interference?', answer: 'Diffraction is wave spreading around obstacles. Interference is superposition of multiple waves. Diffraction patterns result from interference of wavelets from within a single opening.' },
    ],
  },

  'polarization': {
    metaTitle: 'Polarization - Interactive Simulator | Atlas Coach',
    metaDescription: 'Rotate polarizers, observe Malus\'s law, and understand how polarized sunglasses, LCD screens, and 3D movies use the polarization of light.',
    concepts: ['polarization', 'Malus\'s law', 'polarizer', 'linear polarization', 'crossed polarizers'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What does it mean for light to be polarized?', answer: 'Polarized light has its electric field oscillating in a single plane. A polarizer transmits only one orientation, blocking the rest.' },
      { question: 'How do polarized sunglasses reduce glare?', answer: 'Reflected light from flat surfaces is horizontally polarized. Sunglasses with a vertical axis block this glare selectively while transmitting other orientations.' },
    ],
  },

  'photoelectric-effect': {
    metaTitle: 'Photoelectric Effect - Interactive Simulator | Atlas Coach',
    metaDescription: 'Shine light on metal surfaces and eject electrons. Vary frequency and intensity to discover why the photoelectric effect proved light is quantized into photons.',
    concepts: ['photoelectric effect', 'photon energy', 'work function', 'threshold frequency', 'quantum mechanics'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why did Einstein win the Nobel Prize for this?', answer: 'He proposed light consists of discrete energy packets (photons) with E = hf, explaining why only frequency (not intensity) determines whether electrons are ejected. This founded quantum mechanics.' },
      { question: 'What is the work function?', answer: 'The minimum energy to free an electron from a metal surface, typically 2-5 eV. Photons with energy below this cannot eject electrons no matter how bright the light.' },
    ],
  },

  'total-internal-reflection': {
    metaTitle: 'Total Internal Reflection - Interactive Simulator | Atlas Coach',
    metaDescription: 'Guide light through glass and find the critical angle where it all reflects. Understand how fiber optics, diamond brilliance, and prism binoculars work.',
    concepts: ['total internal reflection', 'critical angle', 'fiber optics', 'evanescent wave'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is total internal reflection?', answer: 'When light hits a boundary from a denser to less dense medium above the critical angle, 100% reflects with zero absorption loss. This is the basis of fiber optic communications.' },
      { question: 'Why do diamonds sparkle?', answer: 'Diamond\'s high refractive index (2.42) creates a critical angle of only 24 degrees. Light bounces many times inside before escaping, producing intense brilliance and fire.' },
    ],
  },

  // ================================================================
  // SEMICONDUCTORS & ELECTRONICS
  // ================================================================

  'm-o-s-f-e-t-switching': {
    metaTitle: 'MOSFET Switching - Interactive Simulator | Atlas Coach',
    metaDescription: 'Control a virtual MOSFET transistor. Adjust gate voltage, observe channel formation, and understand the switching behavior powering all modern digital electronics.',
    concepts: ['MOSFET', 'threshold voltage', 'channel formation', 'digital switching', 'CMOS'],
    difficulty: 'advanced',
    estimatedMinutes: 12,
    faqItems: [
      { question: 'What is a MOSFET?', answer: 'A Metal-Oxide-Semiconductor Field-Effect Transistor. A gate voltage controls current between source and drain. It is the fundamental switch in every digital chip.' },
      { question: 'How many transistors are in a modern chip?', answer: 'Over 100 billion. Each switches billions of times per second. The entire digital world runs on MOSFET switching.' },
    ],
  },

  'photolithography': {
    metaTitle: 'Photolithography - Interactive Simulator | Atlas Coach',
    metaDescription: 'Step through the lithography process used to manufacture chips. Expose photoresist, develop patterns, and etch nanometer-scale circuit features.',
    concepts: ['photolithography', 'photoresist', 'mask alignment', 'EUV', 'resolution limit'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'How small can photolithography print?', answer: 'EUV lithography at the 3nm node prints features as small as 5-12 nm, roughly 50 atoms wide. This requires 13.5nm wavelength light and optics accurate to picometers.' },
      { question: 'What is a reticle?', answer: 'A glass plate with a chrome circuit pattern. Light through the clear areas projects the pattern onto the wafer at 4x reduction. Each reticle costs $100K-$500K at leading-edge nodes.' },
    ],
  },

  'chiplets-vs-monoliths': {
    metaTitle: 'Chiplets vs Monoliths - Interactive Simulator | Atlas Coach',
    metaDescription: 'Compare chiplet and monolithic die architectures. Explore yield, cost, interconnect, and performance tradeoffs shaping modern chip packaging decisions.',
    concepts: ['chiplet', 'monolithic die', 'yield', 'advanced packaging', 'interconnect overhead'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What are chiplets?', answer: 'Small modular dies assembled in a package. They improve yield (smaller dies have fewer defects) and allow mixing process nodes (e.g., 3nm compute with 12nm I/O).' },
      { question: 'Who uses chiplets?', answer: 'AMD (Zen 2 and later), Intel (Meteor Lake), and Apple (Ultra chips). Chiplets are becoming the industry standard for large processor designs.' },
    ],
  },

  'a-s-i-cvs-g-p-u': {
    metaTitle: 'ASIC vs GPU - Interactive Comparison | Atlas Coach',
    metaDescription: 'Compare ASIC and GPU architectures for AI and specialized workloads. Adjust parallelism, power, and batch sizes to discover when each wins.',
    concepts: ['ASIC', 'GPU', 'hardware specialization', 'performance per watt', 'design tradeoffs'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'When should you choose an ASIC over a GPU?', answer: 'When running a single well-defined workload at massive scale and power efficiency is critical. GPUs win when workloads change frequently or volumes are low.' },
      { question: 'What is an example of a successful ASIC?', answer: 'Bitcoin miners, Google TPU, Apple Neural Engine, and Tesla FSD chip. Each sacrifices flexibility for 10-100x efficiency at its target workload.' },
    ],
  },

  't-p-uvs-g-p-u': {
    metaTitle: 'TPU vs GPU - Interactive Comparison | Atlas Coach',
    metaDescription: 'Compare Google TPUs and NVIDIA GPUs for deep learning. Explore systolic arrays vs CUDA cores, software ecosystems, and cost-performance tradeoffs.',
    concepts: ['TPU', 'GPU', 'systolic array', 'AI accelerator', 'deep learning hardware'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What makes TPUs different from GPUs?', answer: 'TPUs use systolic arrays optimized for matrix multiplication. GPUs use SIMT cores for diverse parallel workloads. TPUs are more efficient for pure ML but less flexible.' },
      { question: 'Can I use PyTorch on TPUs?', answer: 'Yes, via PyTorch/XLA, though JAX and TensorFlow have more mature TPU support. GPU remains the path of least resistance for PyTorch workflows.' },
    ],
  },

  // ================================================================
  // AI & COMPUTING
  // ================================================================

  'a-i-inference-latency': {
    metaTitle: 'AI Inference Latency - Interactive Simulator | Atlas Coach',
    metaDescription: 'Model end-to-end neural network inference latency. Explore how batch size, model size, quantization, and hardware choice affect response time and throughput.',
    concepts: ['inference latency', 'throughput', 'batch size', 'model optimization', 'serving'],
    difficulty: 'advanced',
    estimatedMinutes: 12,
    faqItems: [
      { question: 'What determines AI inference latency?', answer: 'Model size (parameters), hardware (GPU type, memory bandwidth), batch size, and optimizations (quantization, pruning, KV caching). Memory bandwidth is often the bottleneck.' },
      { question: 'Why does batching improve throughput but hurt latency?', answer: 'Batching amortizes weight-loading cost across multiple requests (better throughput), but each request waits for the batch to fill (worse individual latency).' },
    ],
  },

  'g-p-u-memory-bandwidth': {
    metaTitle: 'GPU Memory Bandwidth - Interactive Simulator | Atlas Coach',
    metaDescription: 'Explore why memory bandwidth often limits AI performance more than compute FLOPS. Simulate data movement between cores and HBM to find your bottleneck.',
    concepts: ['memory bandwidth', 'HBM', 'memory-bound', 'compute-bound', 'roofline model'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is the roofline model?', answer: 'A visual tool plotting performance against arithmetic intensity (FLOPS/byte). Workloads below the diagonal are memory-bound; at the horizontal ceiling, they are compute-bound.' },
      { question: 'Why is HBM essential for AI GPUs?', answer: 'HBM provides 3+ TB/s bandwidth via vertical die stacking, 2-3x more than GDDR. LLM inference is memory-bound, so bandwidth directly determines token generation speed.' },
    ],
  },

  'memory-hierarchy': {
    metaTitle: 'Memory Hierarchy - Interactive Simulator | Atlas Coach',
    metaDescription: 'Navigate the memory hierarchy from registers to disk. Visualize access latencies spanning six orders of magnitude and learn why cache locality matters.',
    concepts: ['memory hierarchy', 'cache', 'latency', 'locality', 'cache miss'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why not just make all memory fast?', answer: 'Fast memory (SRAM) is expensive and physically large per bit. The hierarchy exploits locality: most accesses hit fast caches, giving the illusion of large, fast memory at affordable cost.' },
      { question: 'What is a cache miss?', answer: 'When requested data is not in the cache. An L1 miss hitting L2 costs ~5ns. Missing all caches and going to DRAM costs ~100ns, a 20x penalty.' },
    ],
  },

  // ================================================================
  // SOLAR & ENERGY
  // ================================================================

  'solar-cell': {
    metaTitle: 'Solar Cell - Interactive Simulator | Atlas Coach',
    metaDescription: 'Simulate a solar cell from photon absorption to current generation. Adjust bandgap, temperature, and irradiance to explore IV curves and efficiency limits.',
    concepts: ['photovoltaic effect', 'p-n junction', 'bandgap', 'open circuit voltage', 'short circuit current'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is the maximum theoretical efficiency?', answer: 'The Shockley-Queisser limit: ~33.7% for single-junction silicon. Multi-junction cells exceed 47% in the lab by capturing different spectral bands.' },
      { question: 'How does temperature affect solar cells?', answer: 'Higher temperature reduces voltage and efficiency by ~0.3-0.5% per degree C for silicon. Panels produce more energy in cool, sunny climates.' },
    ],
  },

  'p-v-i-v-curve': {
    metaTitle: 'Solar PV IV Curve - Interactive Simulator | Atlas Coach',
    metaDescription: 'Trace the current-voltage curve of a solar panel. Find the maximum power point, observe shading effects, and understand fill factor and its impact on efficiency.',
    concepts: ['IV curve', 'maximum power point', 'fill factor', 'Voc', 'Isc'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is fill factor?', answer: 'FF = Pmax / (Voc * Isc). Good silicon cells have FF of 0.75-0.85. Higher FF means a more rectangular IV curve and more efficient power extraction.' },
      { question: 'Why does one shaded panel affect the whole string?', answer: 'In series, current must be equal everywhere. One shaded cell limits current for all panels. Bypass diodes route current around shaded cells to prevent severe loss.' },
    ],
  },

  'm-p-p-t': {
    metaTitle: 'MPPT Solar Tracker - Interactive Simulator | Atlas Coach',
    metaDescription: 'Watch MPPT algorithms find the maximum power point in real time. Compare perturb-and-observe, incremental conductance, and global scan methods.',
    concepts: ['MPPT', 'maximum power point', 'perturb and observe', 'DC-DC converter', 'tracking'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'How much does MPPT improve energy harvest?', answer: 'Typically 20-30% more than a fixed-voltage connection. Gains are largest under suboptimal conditions: cold panels, partial shade, low irradiance.' },
      { question: 'MPPT vs PWM: which is better?', answer: 'MPPT uses a DC-DC converter to operate the panel at its optimal voltage. PWM forces panel voltage to match battery voltage, losing 15-30% of potential power.' },
    ],
  },

  'series-parallel-p-v': {
    metaTitle: 'Series vs Parallel Solar Panels - Interactive Simulator | Atlas Coach',
    metaDescription: 'Wire virtual solar panels in series and parallel. Compare voltage, current, shading tolerance, and total power for each wiring configuration in real time.',
    concepts: ['series wiring', 'parallel wiring', 'string voltage', 'shade tolerance', 'bypass diodes'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Series or parallel for my solar system?', answer: 'Series for grid-tied string inverters (high voltage, low current, less wire loss). Parallel for shade-prone installations or microinverter systems. Most large systems use both.' },
      { question: 'What happens if one panel in a string is shaded?', answer: 'Without bypass diodes, it limits current for the entire string and can overheat. With bypass diodes, current routes around it, limiting losses to one panel.' },
    ],
  },

  // ================================================================
  // SPACE & ORBITAL
  // ================================================================

  'orbital-mechanics': {
    metaTitle: 'Orbital Mechanics - Interactive Simulator | Atlas Coach',
    metaDescription: 'Launch satellites into orbit and perform maneuvers. Learn Kepler\'s laws, Hohmann transfers, and gravity assists through hands-on orbital simulation.',
    concepts: ['Kepler\'s laws', 'orbital velocity', 'Hohmann transfer', 'gravity assist', 'delta-v'],
    difficulty: 'advanced',
    estimatedMinutes: 12,
    faqItems: [
      { question: 'How fast must a satellite go?', answer: 'In low Earth orbit (400 km): ~7.66 km/s. Geostationary (35,786 km): ~3.07 km/s. Escape velocity from Earth surface: 11.2 km/s.' },
      { question: 'What is a Hohmann transfer?', answer: 'The most fuel-efficient orbit change between two circular orbits. Two burns: one to enter an elliptical transfer orbit, one to circularize at the target.' },
    ],
  },

  'coriolis-effect': {
    metaTitle: 'Coriolis Effect - Interactive Simulator | Atlas Coach',
    metaDescription: 'Launch projectiles on a rotating Earth and watch them curve. Understand hurricanes, trade winds, and ocean gyres through the Coriolis effect simulation.',
    concepts: ['Coriolis effect', 'rotating reference frame', 'fictitious force', 'cyclone formation'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Does the Coriolis effect affect my sink drain?', answer: 'No. At bathroom scale, Coriolis force is 100,000x weaker than jet and basin shape effects. Drain direction is determined by plumbing geometry, not hemisphere.' },
      { question: 'Why do hurricanes spin?', answer: 'Low pressure draws air inward. Coriolis deflects inflow rightward (Northern Hemisphere), creating counterclockwise rotation. Southern Hemisphere hurricanes spin clockwise.' },
    ],
  },

  // ================================================================
  // MATERIALS
  // ================================================================

  'brownian-motion': {
    metaTitle: 'Brownian Motion - Interactive Simulator | Atlas Coach',
    metaDescription: 'Watch microscopic particles jitter from molecular collisions. Adjust temperature, particle size, and viscosity to explore the random walk that proved atoms exist.',
    concepts: ['Brownian motion', 'random walk', 'diffusion', 'Einstein relation', 'molecular bombardment'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Who discovered Brownian motion?', answer: 'Robert Brown observed it in 1827 with pollen grains. Einstein explained it theoretically in 1905. Perrin confirmed it experimentally in 1908, proving atoms exist.' },
      { question: 'How far does a Brownian particle move?', answer: 'Mean squared displacement grows linearly with time: <x^2> = 2Dt. A 1-micron particle in water diffuses about 1 micron in 0.5 seconds.' },
    ],
  },

  // ================================================================
  // EXPERIMENTS & FUN PHYSICS
  // ================================================================

  'reaction-time': {
    metaTitle: 'Reaction Time Test - Interactive Experiment | Atlas Coach',
    metaDescription: 'Measure your reaction time with precision timing. Understand the neuroscience of sensory processing and compare visual, auditory, and tactile response speeds.',
    concepts: ['reaction time', 'neuroscience', 'sensory processing', 'motor response', 'human factors'],
    difficulty: 'beginner',
    estimatedMinutes: 5,
    faqItems: [
      { question: 'What is the average human reaction time?', answer: 'About 200-250 ms for visual stimuli, 150-200 ms for auditory, and 150 ms for tactile. Athletes can achieve sub-200 ms with training.' },
      { question: 'Can reaction time be improved?', answer: 'Somewhat, through practice and anticipation. Caffeine helps by 5-10%. Sleep deprivation significantly worsens it. Elite athletes read preparatory cues to react faster.' },
    ],
  },

  // ================================================================
  // RF & COMMUNICATIONS
  // ================================================================

  'antenna-gain': {
    metaTitle: 'Antenna Gain - Interactive Simulator | Atlas Coach',
    metaDescription: 'Design antennas and visualize radiation patterns. Adjust element count, spacing, and orientation to maximize gain and understand directivity concepts.',
    concepts: ['antenna gain', 'radiation pattern', 'directivity', 'beamwidth', 'isotropic radiator'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What does antenna gain measure?', answer: 'How much an antenna concentrates energy in a particular direction versus an isotropic radiator. A 10 dBi antenna focuses power 10x in the target direction.' },
      { question: 'Does high gain mean more total power?', answer: 'No. It redistributes the same power into a narrower beam. Higher gain means more concentrated energy in one direction but less coverage elsewhere.' },
    ],
  },

  'link-budget': {
    metaTitle: 'Link Budget Calculator - Interactive Simulator | Atlas Coach',
    metaDescription: 'Calculate wireless link budgets step by step. Account for transmit power, antenna gains, path loss, and receiver sensitivity to determine link feasibility.',
    concepts: ['link budget', 'path loss', 'free space loss', 'fade margin', 'receiver sensitivity'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'What is a link budget?', answer: 'A systematic accounting of all gains and losses: TX power + antenna gains - path loss - cable losses must exceed receiver sensitivity plus required margin.' },
      { question: 'What is fade margin?', answer: 'Extra signal strength beyond the minimum, buffering against temporary fading from multipath, rain, or atmospheric effects. Typical margins are 10-30 dB depending on reliability requirements.' },
    ],
  },

  // ================================================================
  // POWER SYSTEMS
  // ================================================================

  'd-c-d-c-converter': {
    metaTitle: 'DC-DC Converter - Interactive Simulator | Atlas Coach',
    metaDescription: 'Build buck and boost converters. Adjust duty cycle, switching frequency, and load to learn how voltage conversion works in modern power electronics.',
    concepts: ['DC-DC conversion', 'buck converter', 'boost converter', 'duty cycle', 'switching frequency'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Buck vs boost: what is the difference?', answer: 'Buck steps voltage down (Vout < Vin). Boost steps voltage up (Vout > Vin). Both regulate output by varying the duty cycle of a semiconductor switch.' },
      { question: 'Why not use linear regulators?', answer: 'Switching converters achieve 85-98% efficiency. Linear regulators waste excess voltage as heat (efficiency = Vout/Vin), often below 50% for large drops.' },
    ],
  },

  'grid-frequency': {
    metaTitle: 'Grid Frequency - Interactive Simulator | Atlas Coach',
    metaDescription: 'Balance generation and demand to keep grid frequency at 50/60 Hz. Understand frequency droop, spinning reserves, and load-following dynamics in real time.',
    concepts: ['grid frequency', 'supply-demand balance', 'frequency droop', 'grid inertia', 'load following'],
    difficulty: 'intermediate',
    estimatedMinutes: 8,
    faqItems: [
      { question: 'Why must grid frequency stay at 50/60 Hz?', answer: 'Motors, clocks, and industrial equipment depend on stable frequency. Even 0.5 Hz deviation can trigger automatic load shedding to prevent cascading failure.' },
      { question: 'What happens when a power plant trips?', answer: 'Frequency drops as demand exceeds supply. Spinning reserves ramp up in seconds (primary response), then scheduled reserves activate within minutes (secondary response).' },
    ],
  },
};

// ============================================================
// LOOKUP — Used by GameShell to get SEO data for any game slug
// ============================================================

export interface GameSEOResult {
  title: string;
  description: string;
  concepts?: string[];
  difficulty?: string;
  estimatedMinutes?: number;
  faqItems?: GameSEOFAQ[];
}

/**
 * Get SEO data for a game by slug.
 * Falls back to auto-generated data from the slug if not in the map.
 */
export function getGameSEO(slug: string): GameSEOResult {
  const entry = gameSEOData[slug];
  if (entry) {
    return {
      title: entry.metaTitle.replace(/ - .+$/, ''),
      description: entry.metaDescription,
      concepts: entry.concepts,
      difficulty: entry.difficulty,
      estimatedMinutes: entry.estimatedMinutes,
      faqItems: entry.faqItems,
    };
  }

  // Auto-generate from slug
  const title = slug
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  return {
    title,
    description: `Explore ${title} through an interactive simulation. Predict outcomes, experiment with variables, and test your understanding.`,
    estimatedMinutes: 10,
  };
}
